// This file is generated by Tooki Blog CMS.
export interface Friend { id: string; name: string; url: string; description: string; avatar: string; themeColor: string; }

export const friendsData: Friend[] = [
  {
    "id": "friend_1778773192515",
    "name": "win8",
    "url": "w1n8.cc",
    "avatar": "https://w1n8.cc/images/tomori.jpg",
    "description": "高数之神",
    "themeColor": "#6366f1"
  },
  {
    "id": "friend_1778772929590",
    "name": "uky",
    "url": "https://ukyblog-s2.vercel.app/",
    "avatar": "https://bu.dusays.com/2026/05/12/6a02aba5ae116.jpg",
    "description": "web界的goat\n最阴最爱装菜的",
    "themeColor": "#6366f1"
  },
  {
    "id": "yanxisishi",
    "name": "Yanxisishi",
    "description": "web界的卡密",
    "avatar": "https://blog.yanxisishi.top/favicon.ico",
    "url": "https://blog.yanxisishi.top/",
    "themeColor": "rgba(56, 189, 248, 0.5)"
  },
  {
    "id": "52pojie",
    "name": "吾爱破解",
    "description": "软件安全、逆向分析和工具交流论坛",
    "avatar": "https://www.52pojie.cn/favicon.ico",
    "url": "https://www.52pojie.cn/",
    "themeColor": "rgba(99, 102, 241, 0.5)"
  },
  {
    "id": "kanxue",
    "name": "看雪论坛",
    "description": "安全研究、逆向工程和漏洞分析社区",
    "avatar": "https://bbs.kanxue.com/favicon.ico",
    "url": "https://bbs.kanxue.com/",
    "themeColor": "rgba(34, 197, 94, 0.5)"
  },
  {
    "id": "runoob-tools",
    "name": "菜鸟工具",
    "description": "编码转换、格式化和在线小工具",
    "avatar": "https://uutool.cn/assets/images/favicon.jpg",
    "url": "https://c.runoob.com/",
    "themeColor": "rgba(249, 115, 22, 0.5)"
  },
  {
    "id": "bilibili",
    "name": "Bilibili",
    "description": "视频、学习和技术内容平台",
    "avatar": "https://www.bilibili.com/favicon.ico",
    "url": "https://www.bilibili.com/",
    "themeColor": "rgba(236, 72, 153, 0.5)"
  }
];